-- ============================================================
-- EBS PROJECT TRACKER — Seed Data
-- Run this AFTER supabase_schema.sql
-- ============================================================

INSERT INTO projects (project_number, project_name, objective, dept_module, business_owner, priority, status, phase, est_start, start_date, end_date, percent_complete, total_cost_kwd, business_impact, cost_remarks, dependencies, key_risks, mitigation, notes_updates, actions_needed) VALUES
(1, 'Ecommerce Integration-Soft Launch', 'Deliver a fully operational E-Commerce ecosystem by integrating Salesforce (Commerce & Marketing Cloud) with D-365 ERP and Clientele in Retail POS - delivered in two phases - to drive digital revenue, customer loyalty and an enhanced in-store experience including self-checkout.', 'EBS/ERP Integration', 'Imad Najibeddine', 'Critical', 'Delayed', 'UAT', NULL, '2025-12', '2026-05', '80', 0, 'High', 'Included in initial ERP implementation scope', 'SF Partner - UAT instance + Development completion', 'UAT instance not ready and SF Partner development incomplete - testing cannot begin until both are delivered', 'SF Partner committed delivery by 14-April-2026. Daily status updates/calls scheduled to track progress', '1. ERP–eCommerce integration is on track; however, the overall project timeline has been delayed. Go-live date has been pushed back due to master data readiness issues. 2. UAT sign-off pending', '1. Confirm UAT readiness delivery date from SF Partner. 2. Prepare integration test cases and complete testing by April 25. 3. Prepare for go-live readiness by April 30.'),

(2, 'Ecommerce Integration Project-Stage 2', 'Deliver a fully operational E-Commerce ecosystem by integrating Salesforce (Commerce & Marketing Cloud) with D-365 ERP and Clientele in Retail POS - delivered in two phases - to drive digital revenue, customer loyalty and an enhanced in-store experience including self-checkout.', 'EBS/ERP Integration', 'Imad Najibeddine', 'High', 'On Track', 'Initiation', '2026-05', '2026-05', '2026-07', '0', 0, 'High', 'To be Estimated', 'All BUs, Salesforce Partner, ERP Partner, Stage 1 Completion', 'Dependent on Stage 1 completion — delay impacts Stage 2 kickoff', 'Weekly Stage 1 milestone tracking - Buffer of 2 weeks built into Stage 2 plan', 'Stage 2 planned start: May 2026 subject to Stage 1 go-live', NULL),

(3, 'Ecommerce Integration Project-Phase 2', 'Deliver a fully operational E-Commerce ecosystem by integrating Salesforce (Commerce & Marketing Cloud) with D-365 ERP and Clientele in Retail POS - delivered in two phases - to drive digital revenue, customer loyalty and an enhanced in-store experience including self-checkout.', 'EBS/ERP Integration', 'Imad Najibeddine', 'High', 'On Track', 'Initiation', '2026-07', '2026-07', '2026-10', '0', 0, 'High', 'To be Estimated', 'All BUs, Salesforce Partner, ERP Partner, Stage 2 Completion', 'Dependent on Stage 2 completion — delay impacts Phase 2 kickoff', 'Weekly Stage 2 milestone tracking - Buffer of 2 weeks built into Phase 2 plan', 'Phase 2 planned start: July 2026 subject to Stage 2 go-live', NULL),

(4, 'Sales Forecast Functionality', 'Develop a centralized sales forecast capability at item and channel level to enable real-time visibility, integrated reporting, and data-driven decision making across the organization', 'EBS/Demand Planning', 'Ahmad Baddar', 'High', 'Completed', 'Closed', NULL, '2025-12', '2026-02', '100', 0, 'High', 'Consumed from ERP Support Hours', 'Demand planner', NULL, NULL, 'Successfully deployed Feb 26. Post-impl review done', NULL),

(5, 'Power BI Reports', 'Continuously design, develop, and deliver Power BI reports and dashboards across all business units - Visual insights that support informed decision making, performance monitoring, and strategic planning across the organization', 'EBS/BI & Analytics', 'All BUs', 'High', 'On Track', 'Execution', NULL, '2026-01', '2026-12', 'Ongoing', 0, 'High', 'EBS/Consumed from support hours', 'All BUs', NULL, NULL, 'Ongoing BI programme delivering Power BI reports and dashboards across all business units - reports cover sales, finance, inventory, operations, and retail performance.', NULL),

(6, 'IMEI Tracking', 'Develop IMEI tracking capability across all sales channels for new mobile categories - enabling end-to-end device traceability from point of sale to service', 'EBS / Sales Channels', 'Vikas Arora', 'High', 'On Track', 'Execution', NULL, '2026-02', '2026-04', '95', 0, 'High', 'Consumed from ERP Support Hours', 'Category Team, ERP Partner', NULL, NULL, 'Development and Testing Completed', '1. Train showroom & warehouse staff on IMEI capture process 2. Go-live directly tied to showroom opening / mobile category launch'),

(7, 'Footfall analysis solution', 'Implement a footfall analysis solution across all retail locations to capture and measure real-time customer traffic', 'EBS', 'Mohamed Hashem', 'High', 'On Track', 'Initiation', NULL, '2026-03', '2026-05', '10', 8500, 'High', 'Estimated Cost. Actuals may vary based on camera requirements', 'Internal PO / Contract approval, Procurement and Legal sign-off, Vendor mobilization(Jarvis/ERP), Scope Definition', NULL, NULL, '1. Vendor selected and finalized 2. Solution evaluated and references checked 3. Awaiting internal PO and contract execution', '1. Expedite PO approval 2. Schedule project kick-off meeting with vendor immediately after contract signing'),

(8, 'Service Contracts — Subscription Billing & AMC Management', 'Establish a fully automated service contract management solution that empowers the business to manage annual maintenance contracts, drive timely invoicing, ensure accurate revenue recognition, and maintain complete visibility over work orders', 'EBS/Subscription Billing', 'Toufic Fakhani', 'Medium', 'On Track', 'UAT', NULL, '2026-03', '2026-04', '65', 0, 'High', 'Consumed from ERP Support Hours', 'Service team, Finance', 'UAT defects or gaps identified by users may require rework and delay in user sign-off will push go-live date', 'Daily UAT progress tracking and EBS team on standby for immediate fixes/clarifications during testing period', '1. User training completed successfully 2. Business users currently in UAT phase testing full contract lifecycle 3. Go-live subject to UAT sign-off', 'Track and resolve UAT issues, get UAT sign-off from Business Owner and Finance, confirm go-live date once testing is complete'),

(9, 'Stock Take Batch Tracking - Handheld Enhancements', 'Enhance the handheld stock take application to enable accurate batch tracking during the physical stock take process', 'EBS/Handheld solution', 'Inventory Controller', 'Medium', 'On Track', 'UAT', NULL, '2025-12', '2026-04', '85', 650, 'Medium', NULL, 'UAT sign-off on sample batch data', '1. Physical expiry dates and system expiry dates are not matching across batch items 2. Operations team has not yet resolved the data discrepancy 3. Sign-off is blocked until mismatches are corrected', '1. Operations team engaged and aligned on fixing expiry date mismatches 2. Daily follow-up with operations team on correction progress', '1. Handheld enhancements completed and delivered 2. Stock take team trained successfully 3. UAT done using sample batch data 4. Expiry date mismatch between physical stock and system identified as open issue', 'Obtain formal UAT sign-off to close project and unblock ERP integration project kick-off'),

(10, 'Stock Take - Integration with ERP', 'Integrate the stock take handheld application with ERP to enable real-time synchronization, eliminating manual reconciliation', 'EBS/ERP Integration', 'Inventory Controller', 'Medium', 'On Track', 'Initiation', '2026-06', '2026-06', '2026-07', '0', 0, 'Medium', 'To be Estimated', NULL, 'Stock take batch tracking signoff', NULL, 'Project is in pipeline', 'Stock Take Batch Tracking sign-off'),

(11, 'People Engagement Platform', 'Deploy an enterprise people engagement solution that establishes a unified internal communications platform', 'EBS/Internal Communications', 'Richlene', 'Medium', 'On Track', 'Initiation', NULL, '2026-03', '2026-08', '5', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, 'Project initiated by HR and demo scheduled for next week', 'Vendor and solution assessment'),

(12, 'New Showroom Rollout- Setup & Support', 'Plan, setup, and deliver end-to-end infrastructure for Sabah Al Salem store covering D365, POS systems, network, attendance, IT infrastructure, and CCTV', 'EBS/Retail Operations', 'Mohamed Hashem', 'High', 'Completed', 'Closed', NULL, '2026-02', '2026-03', '100', 0, 'High', NULL, NULL, NULL, NULL, NULL, NULL),

(13, 'Service tech mobile app', 'Deliver a field service mobile application that empowers technicians to manage work orders on the go capturing real-time job status updates, payments, and customer site photographs', 'EBS/field Service Management', 'Toufic Fakhani', 'Medium', 'Delayed', 'UAT', NULL, '2025-11', '2026-05', '75', 0, 'Medium', 'Included in initial ERP implementation scope', 'Development team handover to EBS by 15 April for end to end testing', NULL, NULL, '1. Original go-live February 2026 2. Delayed due to resource reprioritization to eCommerce project 3. Post-demo change requests from service department incorporated', '1. Handover to EBS for testing expected 15 April 2026 2. UAT to follow immediately 3. Revised go-live target June 2026'),

(14, 'Price check app', 'Develop a price check application for retail operations to enable real-time visibility of pricing and stock availability across all retail locations', 'EBS/Retail Operations', 'Mohamed Hashem', 'Medium', 'On Track', 'Execution', NULL, '2025-12', '2026-05', '70', 0, 'Medium', 'Included in initial ERP implementation scope', NULL, 'Scope of changes must be controlled to avoid further additions', 'Change freeze to be applied once current round of post-demo changes are complete', '1. Initial application development completed and demo conducted with retail operations team 2. Post-demo change requests received and currently under development', 'Confirm completion date of post-demo change requests from dev team'),

(15, 'Transfer order app', 'Develop a mobile transfer order application for retail operations to enable seamless stock transfers between locations', 'EBS/Retail Operations', 'Mohamed Hashem', 'Medium', 'On Track', 'Execution', NULL, '2025-11', '2026-05', '80', 0, 'Medium', 'Included in initial ERP implementation scope', NULL, 'Scope of changes must be controlled to avoid further additions', 'Change freeze to be applied once current round of post-demo changes are complete', '1. Initial application development completed and demo conducted 2. Post-demo change requests received and currently under development', 'Confirm completion date of post-demo change requests from dev team'),

(16, 'Payroll Integration', 'Integrate the payroll system with ERP to enable automated payroll data exchange, eliminating manual exchange of data and automated journal postings', 'EBS/Payroll', 'Richlene & Gurjeet', 'Medium', 'On Track', 'Planning', NULL, '2026-03', '2026-06', '30', 0, 'Medium', 'Included in initial ERP implementation scope', 'Enfinity Partner, ERP Partner, P&C', 'Resource alignment from both payroll partner and ERP partner is a hard dependency', 'Resource commitment to be confirmed from both partners before project kick-off', '1. Initial integration development completed by both parties during 2025 ERP implementation 2. Project paused and now being restarted March 2026', '1. Confirm resource availability from payroll partner and ERP partner 2. Review prior integration development for reusability'),

(17, 'Talabat Integration', 'Integrate ERP with the Talabat platform to activate and scale a new digital sales channel', 'EBS/ERP Integration', 'Mohamad El Habbal', 'Medium', 'On Hold', 'Initiation', NULL, '2026-01', '2026-08', '5', 0, 'Medium', 'To be Estimated', 'ERP Partner, Talabat Partner', NULL, NULL, 'Project initiated and one scoping meeting held with integration partner. Project paused due to other business priorities', 'Re-engage with business owner and understand the priorities and expected launch date'),

(18, 'Dealer Orders- Prepayments Rollout', 'Implement sales prepayment functionality in ERP to resolve the current practice of premature dealer order invoicing', 'EBS/ERP Order Mgmt', 'Mohamad El Habbal', 'Medium', 'On Track', 'Execution', NULL, '2026-03', '2026-05', '25', 0, 'Medium', 'Consumed from ERP Support Hours', 'ERP Partner', NULL, NULL, 'Project initiated to address current business pain point of premature dealer order invoicing for collections and commission.', 'Complete customization and configuration'),

(19, 'PO Workflow Matrix and Mobile Approvals', 'Enable purchase budget controls, configure the purchase order approval workflow matrix, and implement mobile PO approvals in ERP', 'EBS/Procurement', 'Gurjeet', 'High', 'On Track', 'Execution', NULL, '2026-03', '2026-05', '45', 0, 'Medium', 'Consumed from ERP Support Hours', '1. Mobile device compatibility confirmed for all approvers 2. Budget data loaded in ERP before go-live', 'Post-demo change requests or approval matrix revisions could push the timeline', 'Budget uploads to be confirmed and locked with Finance', 'ERP setups underway covering purchase budget enablement, PO approval workflow matrix configuration, and mobile approval implementation', 'Initial demo scheduled 24 April 2026. Go-live targeted 1 May 2026'),

(20, 'Extended Warranty & Installation Charges - Retail & eCommerce', 'Implement extended warranty and installation charge functionality across retail POS and eCommerce platforms', 'EBS/Order Management', 'Mohamed Hashem/Imad Najibeddine', 'High', 'On Track', 'Execution', NULL, '2026-04', '2026-05', '40', 0, 'High', 'Consumed from ERP Support Hours', 'Ecom Platform readiness to sell extended warranty', NULL, NULL, '1. Financial treatment changes as role revised from principal to agent 2. Development underway to handle extended warranty packages and installation charges', 'Complete development, test across both retail and eCommerce channels, UAT with retail ops and eCommerce teams'),

(21, 'Digital price tags Integration', 'Implement digital price tag solution across retail showrooms to replace manual paper price labels', 'EBS/Retail Operations', 'Mohamed Hashem', 'High', 'On Track', 'Initiation', NULL, '2026-03', '2026-06', '10', 0, 'High', 'To be Estimated', NULL, NULL, NULL, 'Vendor and solution assessment currently underway', 'Complete vendor assessment, confirm ERP integration capability per vendor. Select vendor and initiate PO and contract process'),

(22, 'Integration with Last Mile Delivery', 'Integrate ERP with last mile delivery partner to enable automated order fulfilment and same day delivery capability', 'EBS/Logistics & Fulfillment', 'Imad Najibeddine', 'Medium', 'On Hold', 'Initiation', '2026-07', '2026-07', '2026-06', '0', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, 'Project has not started yet and is formally dependent on eCommerce Phase 2 kick-off', NULL),

(23, 'QR for pending Deliveries', 'Develop a QR code generation solution to track partial deliveries of indoor and outdoor units', 'EBS/Warehouse Operations', 'Mohamed Kamal', 'Low', 'On Track', 'Execution', NULL, '2026-04', '2026-07', '35', 0, 'Medium', 'Consumed from ERP Support Hours', 'Labels availability', NULL, NULL, NULL, 'Complete development'),

(24, 'Asset Management', 'Implement an asset management solution to centrally track and manage the complete lifecycle of all EBS assets across the organization', 'EBS Operations', 'Thulasi Gonuguntala', 'Low', 'On Track', 'Initiation', NULL, '2026-04', '2026-06', '10', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, NULL, 'Vendor not yet selected- Demo and assessment ongoing'),

(25, 'Sophos MDR-Cyber security upgrade', 'Implement Sophos Managed Detection and Response to enhance the organization cybersecurity posture', 'EBS - Cybersecurity & Infrastructure', 'Thulasi Gonuguntala', 'High', 'On Track', 'Execution', NULL, '2026-01', '2026-04', '90', 8400, 'High', NULL, NULL, NULL, NULL, 'Deploying Sophos Managed Detection and Response across all organizational endpoints and infrastructure.', NULL),

(26, 'Digital Signature', 'Implement a digital signature solution to enable senior management to review and sign documents electronically', 'EBS/Document Management', 'Richlene', 'Low', 'On Track', 'Initiation', NULL, '2026-04', '2026-05', '10', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, 'Trial period is time-limited - decision on licensing must be made before trial expires', '1. Collect senior management feedback on trial 2. Confirm license count and type required 3. Procure licenses upon trial sign-off'),

(27, 'Vansales-Credit Operations', 'Enable credit operations within the van sales module by coordinating with the van sales vendor, Finance, and FMCG team', 'EBS/Vansales', 'Sayed Helal', 'Medium', 'On Track', 'Execution', NULL, '2026-04', '2026-04', '50', 0, 'Medium', NULL, 'Van sales vendor confirmation of required setups', NULL, NULL, 'Partner coordination meeting concluded', 'Finalize and upload master data'),

(28, 'Helpdesk Upgrade', 'Enhance the ManageEngine helpdesk solution with additional features to improve end user experience, enforce SLA tracking and compliance', 'EBS Service Management', 'Thulasi Gonuguntala', 'Low', 'On Track', 'Initiation', NULL, '2026-04', '2026-06', '10', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, NULL, 'Vendor not yet selected- Demo and assessment ongoing'),

(29, 'International barcodes rollout', 'Implement international barcode standards across the organization', 'EBS/Product Management', 'Mohamad Al Habbal', 'Low', 'Completed', 'Closed', NULL, '2026-03', '2026-04', '100', 395, 'Medium', NULL, NULL, NULL, NULL, NULL, NULL),

(30, 'Service Request-Auto Creation', 'Develop and implement automated service request creation functionality', 'EBS/Service Operations', 'Toufic Fakhani', 'Medium', 'On Hold', 'Initiation', '2026-08', '2026-08', '2026-10', '0', 0, 'Medium', 'To be Estimated', NULL, NULL, NULL, NULL, NULL);

-- Seed milestones for Project 1 (Ecommerce Integration-Soft Launch)
INSERT INTO milestones (project_id, milestone_number, deliverable, target_date, actual_date, development_status, uat_status, dependencies, owner, remarks) VALUES
((SELECT id FROM projects WHERE project_number = 1), 1, 'Product Master', NULL, NULL, 'Completed', 'Pending', '1. Master data to be uploaded by UTC 2. UAT instance preparation to be completed by C4 Nexus', 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 2, 'Category Master', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 3, 'Customer Master', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 4, 'Inventory', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 5, 'Price Book', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 6, 'SF to D365-Sales order Export', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 7, 'Payment Journal', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 8, 'SF to D365-Order Status Update', NULL, NULL, 'Completed', 'Pending', NULL, 'TSC', NULL),
((SELECT id FROM projects WHERE project_number = 1), 9, 'Master Data Upload', NULL, NULL, 'In Progress', 'Not Started', NULL, 'Jeswin', NULL),
((SELECT id FROM projects WHERE project_number = 1), 10, 'User Training', NULL, NULL, 'Not Started', 'Not Started', NULL, NULL, NULL);

-- Seed milestones for Project 5 (Power BI Reports)
INSERT INTO milestones (project_id, milestone_number, deliverable, target_date, actual_date, development_status, uat_status, dependencies, owner, remarks) VALUES
((SELECT id FROM projects WHERE project_number = 5), 1, 'The Lines Report (IT Internal)', NULL, NULL, 'Completed', 'Passed', NULL, 'EBS', NULL),
((SELECT id FROM projects WHERE project_number = 5), 2, 'Sales vs Forecast', '2026-04-19', NULL, 'In Progress', 'Not Started', NULL, 'Management', 'Priority 1'),
((SELECT id FROM projects WHERE project_number = 5), 3, 'Forecast by Qty item level Report', NULL, NULL, 'Completed', 'Passed', NULL, 'Ahmed Baddar', NULL),
((SELECT id FROM projects WHERE project_number = 5), 4, 'DSR BY CHANNEL', NULL, NULL, 'Completed', 'Passed', NULL, 'CFO', NULL),
((SELECT id FROM projects WHERE project_number = 5), 5, 'DSR BY BU', NULL, NULL, 'Completed', 'Passed', NULL, 'CFO', NULL),
((SELECT id FROM projects WHERE project_number = 5), 6, 'DSR BY CATEGORY', NULL, NULL, 'Completed', 'Passed', NULL, 'CFO', NULL),
((SELECT id FROM projects WHERE project_number = 5), 7, 'DSR BY BRANDS', NULL, NULL, 'Completed', 'Passed', NULL, 'CFO', NULL),
((SELECT id FROM projects WHERE project_number = 5), 8, 'DISTRIBUTION DASHBOARD', '2026-04-26', NULL, 'In Progress', 'Not Started', NULL, 'Habbal', 'Priority 2'),
((SELECT id FROM projects WHERE project_number = 5), 9, 'DISTRIBUTION CATEGORY ANALYSIS', '2026-04-26', NULL, 'In Progress', 'Not Started', NULL, 'Habbal', 'Priority 3'),
((SELECT id FROM projects WHERE project_number = 5), 10, 'DETAILED DISTRIBUTION REPORT', '2026-04-26', NULL, 'In Progress', 'Not Started', NULL, 'Habbal', 'Priority 4'),
((SELECT id FROM projects WHERE project_number = 5), 11, 'DISTRIBUTION MTD/YTD', '2026-04-26', NULL, 'In Progress', 'Not Started', NULL, 'Habbal', 'Priority 5'),
((SELECT id FROM projects WHERE project_number = 5), 12, 'DISTRIBUTION COMPARISON SHEET', '2026-04-30', NULL, 'Not Started', 'Not Started', NULL, 'Habbal', 'Priority 6'),
((SELECT id FROM projects WHERE project_number = 5), 13, 'MAINTENANCE DASHBOARD', '2026-05-09', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 7'),
((SELECT id FROM projects WHERE project_number = 5), 14, 'MAINTENANCE ITEM DETAILS', '2026-05-09', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 8'),
((SELECT id FROM projects WHERE project_number = 5), 15, 'MAINTENANCE CUSTOMER DETAILS', '2026-05-09', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 9'),
((SELECT id FROM projects WHERE project_number = 5), 16, 'MAINTENANCE DETAILED REPORT', '2026-05-09', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 10'),
((SELECT id FROM projects WHERE project_number = 5), 17, 'INSTALLATION DASHBOARD', '2026-05-17', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 11'),
((SELECT id FROM projects WHERE project_number = 5), 18, 'INSTALLATION ITEM DETAILS', '2026-05-17', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 12'),
((SELECT id FROM projects WHERE project_number = 5), 19, 'INSTALLATION CUSTOMER DETAILS', '2026-05-17', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 13'),
((SELECT id FROM projects WHERE project_number = 5), 20, 'INSTALLATION DETAILED REPORT', '2026-05-17', NULL, 'Not Started', 'Not Started', NULL, 'Toufic', 'Priority 14'),
((SELECT id FROM projects WHERE project_number = 5), 21, 'HA/RAC DASHBOARD', '2026-05-24', NULL, 'Not Started', 'Not Started', NULL, 'Walid', 'Priority 15'),
((SELECT id FROM projects WHERE project_number = 5), 22, 'HA/RAC DETAILED', '2026-05-24', NULL, 'Not Started', 'Not Started', NULL, 'Walid', 'Priority 16'),
((SELECT id FROM projects WHERE project_number = 5), 23, 'HA/RAC ANALYSIS', '2026-05-31', NULL, 'Not Started', 'Not Started', NULL, 'Walid', 'Priority 17'),
((SELECT id FROM projects WHERE project_number = 5), 24, 'HA/RAC COMPARISON', '2026-05-31', NULL, 'Not Started', 'Not Started', NULL, 'Walid', 'Priority 18'),
((SELECT id FROM projects WHERE project_number = 5), 25, 'HA/RAC INSIGHTS', '2026-05-31', NULL, 'Not Started', 'Not Started', NULL, 'Walid', 'Priority 19');
